// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"gin-web/app/handler"
	"gin-web/internal/agent"
	"gin-web/internal/dao"
	"gin-web/internal/dao/article"
	"gin-web/internal/dao/category"
	"gin-web/internal/dao/comment"
	"gin-web/internal/dao/link"
	"gin-web/internal/dao/option"
	"gin-web/internal/dao/tag"
	"gin-web/internal/dao/user"
	"gin-web/internal/service"
	article2 "gin-web/internal/service/article"
	"gin-web/internal/service/auth"
	category2 "gin-web/internal/service/category"
	comment2 "gin-web/internal/service/comment"
	dashboard2 "gin-web/internal/service/dashboard"
	link2 "gin-web/internal/service/link"
	option2 "gin-web/internal/service/option"
	server2 "gin-web/internal/service/server"
	tag2 "gin-web/internal/service/tag"
	"gin-web/pkg/boostrap"
)

// Injectors from wire.go:

func NewAppContainer() *AppContainer {
	db := boostrap.InitDBEngine()
	articleDao := article.NewArticleDao(db)
	categoryDao := category.NewCategoryDao(db)
	commentDao := comment.NewCommentDao(db)
	linkDao := link.NewLinkDao(db)
	optionDao := option.NewOptionDao(db)
	tagDao := tag.NewTagDao(db)
	userDao := user.NewUserDao(db)
	daos := &dao.Daos{
		Article:  articleDao,
		Category: categoryDao,
		Comment:  commentDao,
		Link:     linkDao,
		Option:   optionDao,
		Tag:      tagDao,
		User:     userDao,
	}
	articleService := article2.NewArticleService(daos)
	authService := auth.NewAuthService(daos)
	categoryService := category2.NewCategoryService(daos)
	optionService := option2.NewOptionService(daos)
	commentService := comment2.NewCommentService(daos, optionService)
	dashboardService := dashboard2.NewDashboardService(daos)
	linkService := link2.NewLinkService(daos)
	tagService := tag2.NewTagService(daos)
	serverService := server2.NewServerService()
	services := &service.Services{
		Agent:     agent.NewServiceFromConfig(articleService),
		Article:   articleService,
		Auth:      authService,
		Category:  categoryService,
		Comment:   commentService,
		Dashboard: dashboardService,
		Link:      linkService,
		Option:    optionService,
		Server:    serverService,
		Tag:       tagService,
	}
	commonHandler := handler.NewCommonHandler(services)
	agentHandler := handler.NewAgentHandler(services)
	healthHandler := handler.NewHealthHandler(db)
	authHandler := handler.NewAuthHandler(services)
	articleHandler := handler.NewArticleHandler(services)
	categoryHandler := handler.NewCategoryHandler(services)
	tagHandler := handler.NewTagHandler(services)
	commentHandler := handler.NewCommentHandler(services)
	dashboardHandler := handler.NewDashboardHandler(services)
	linkHandler := handler.NewLinkHandler(services)
	serverHandler := handler.NewServerHandler(services)
	uploadHandler := handler.NewUploadHandler()
	handlers := &handler.Handlers{
		Agent:     agentHandler,
		Common:    commonHandler,
		Health:    healthHandler,
		Auth:      authHandler,
		Article:   articleHandler,
		Category:  categoryHandler,
		Tag:       tagHandler,
		Comment:   commentHandler,
		Dashboard: dashboardHandler,
		Link:      linkHandler,
		Server:    serverHandler,
		Upload:    uploadHandler,
	}
	appContainer := &AppContainer{
		Handlers: handlers,
	}
	return appContainer
}

// wire.go:

type AppContainer struct {
	Handlers *handler.Handlers
}
